import 'models.dart';

const subjects = ['English Grammar', 'General Knowledge', 'Pakistan Affairs', 'Current Affairs', 'Mathematics', 'Computer Science'];

List<Question> buildQuestions() {
  final banks = <String, List<List<String>>>{
    'English Grammar': [['Choose the correct plural of “child”.', 'Childs|Children|Childes|Childrens', 'Children'], ['Which word is an adjective?', 'Quickly|Honesty|Bright|Run', 'Bright'], ['Select the correct tense: She ___ to school every day.', 'go|goes|going|gone', 'goes'], ['A sentence that asks something is called a…', 'Statement|Command|Question|Phrase', 'Question'], ['Choose the synonym of “rapid”.', 'Slow|Fast|Weak|Late', 'Fast'], ['Which is a pronoun?', 'Table|They|Blue|Sing', 'They'], ['Select the correct article: ___ hour.', 'A|An|The|No article', 'An'], ['What is the opposite of “ancient”?', 'Old|Modern|Historic|Past', 'Modern'], ['Identify the adverb: He spoke softly.', 'He|Spoke|Softly|None', 'Softly'], ['Which is a conjunction?', 'And|Under|Beautiful|Walk', 'And'], ['The past tense of “write” is…', 'Writed|Written|Wrote|Writing', 'Wrote'], ['A group of words with complete meaning is a…', 'Letter|Sentence|Syllable|Prefix', 'Sentence'], ['Choose the correctly spelled word.', 'Necessary|Necesary|Neccessary|Necassary', 'Necessary'], ['“Wow!” is an example of a/an…', 'Interjection|Article|Verb|Noun', 'Interjection'], ['Which word is a preposition?', 'Across|Happy|Think|They', 'Across']],
    'General Knowledge': [['What is the largest ocean?', 'Atlantic|Indian|Pacific|Arctic', 'Pacific'], ['How many continents are there?', 'Five|Six|Seven|Eight', 'Seven'], ['Which planet is known as the Red Planet?', 'Venus|Mars|Jupiter|Mercury', 'Mars'], ['What is the chemical symbol for gold?', 'Ag|Au|Fe|Go', 'Au'], ['Who painted the Mona Lisa?', 'Van Gogh|Picasso|Leonardo da Vinci|Monet', 'Leonardo da Vinci'], ['What is the hardest natural substance?', 'Iron|Diamond|Quartz|Steel', 'Diamond'], ['Which organ pumps blood?', 'Lung|Brain|Heart|Liver', 'Heart'], ['How many sides has a hexagon?', 'Five|Six|Seven|Eight', 'Six'], ['What gas do plants absorb?', 'Oxygen|Nitrogen|Carbon dioxide|Hydrogen', 'Carbon dioxide'], ['The Sahara is a…', 'River|Desert|Mountain|Forest', 'Desert'], ['What is H2O commonly called?', 'Salt|Water|Oxygen|Hydrogen', 'Water'], ['Which instrument measures temperature?', 'Barometer|Thermometer|Compass|Altimeter', 'Thermometer'], ['The currency of Japan is…', 'Yuan|Won|Yen|Ringgit', 'Yen'], ['Which animal is the fastest on land?', 'Lion|Cheetah|Horse|Eagle', 'Cheetah'], ['What is the smallest prime number?', '0|1|2|3', '2']],
    'Pakistan Affairs': [['What is the capital of Pakistan?', 'Lahore|Karachi|Islamabad|Peshawar', 'Islamabad'], ['Pakistan gained independence in…', '1940|1947|1956|1971', '1947'], ['The national language of Pakistan is…', 'Punjabi|Urdu|Sindhi|English', 'Urdu'], ['Who is called the Father of the Nation?', 'Allama Iqbal|Liaquat Ali Khan|Quaid-e-Azam|Sir Syed', 'Quaid-e-Azam'], ['Pakistan’s national poet is…', 'Faiz Ahmed Faiz|Allama Iqbal|Ghalib|Hafeez', 'Allama Iqbal'], ['The highest mountain in Pakistan is…', 'Nanga Parbat|K2|Broad Peak|Rakaposhi', 'K2'], ['The first constitution was made in…', '1956|1962|1973|1947', '1956'], ['The national flower is…', 'Rose|Jasmine|Tulip|Sunflower', 'Jasmine'], ['Which city is called City of Lights?', 'Lahore|Islamabad|Karachi|Quetta', 'Karachi'], ['The Indus River flows into the…', 'Arabian Sea|Red Sea|Bay of Bengal|Caspian Sea', 'Arabian Sea'], ['Pakistan has how many provinces?', 'Three|Four|Five|Six', 'Four'], ['Minar-e-Pakistan is in…', 'Lahore|Multan|Islamabad|Sukkur', 'Lahore'], ['The national animal is…', 'Markhor|Lion|Snow leopard|Himalayan bear', 'Markhor'], ['Objective Resolution was passed in…', '1940|1949|1956|1973', '1949'], ['The largest province by area is…', 'Punjab|Sindh|Balochistan|KPK', 'Balochistan']],
    'Current Affairs': [['Which organization publishes the World Economic Outlook?', 'UN|IMF|WTO|WHO', 'IMF'], ['The headquarters of the UN is in…', 'Geneva|New York|London|Paris', 'New York'], ['WHO primarily works in…', 'Health|Trade|Education|Banking', 'Health'], ['Climate change is strongly linked to increased…', 'Glaciers|Greenhouse gases|Oxygen|Rainforests', 'Greenhouse gases'], ['The currency used by many EU nations is…', 'Dollar|Pound|Euro|Franc', 'Euro'], ['A sustainable energy source is…', 'Coal|Solar|Petrol|Gas', 'Solar'], ['The SDGs were adopted by the…', 'UN|NATO|OPEC|SAARC', 'UN'], ['Artificial intelligence refers to machines that…', 'Sleep|Mimic intelligence|Only calculate|Grow', 'Mimic intelligence'], ['A pandemic affects…', 'One family|Many countries|One city only|Animals only', 'Many countries'], ['The Paris Agreement addresses…', 'Climate|Sports|Trade|Space', 'Climate'], ['Which is a renewable resource?', 'Wind|Coal|Oil|Natural gas', 'Wind'], ['Cybersecurity protects…', 'Data and systems|Roads|Crops|Buildings only', 'Data and systems'], ['The study of population is…', 'Geology|Demography|Biology|Cartography', 'Demography'], ['A budget deficit means spending is…', 'Less than income|More than income|Zero|Saved', 'More than income'], ['Vaccines help develop…', 'Immunity|Hunger|Height|Sleep', 'Immunity']],
    'Mathematics': [['What is 12 × 8?', '86|96|108|88', '96'], ['What is the square root of 144?', '10|11|12|14', '12'], ['A triangle has angles totaling…', '90°|180°|270°|360°', '180°'], ['What is 15% of 200?', '15|20|30|35', '30'], ['If x + 7 = 12, x equals…', '3|4|5|6', '5'], ['The perimeter of a square of side 4 is…', '8|12|16|20', '16'], ['What is 3/4 as a decimal?', '0.25|0.5|0.75|1.25', '0.75'], ['The next prime after 7 is…', '8|9|10|11', '11'], ['What is 2³?', '6|8|9|12', '8'], ['Average of 4, 6 and 8 is…', '5|6|7|8', '6'], ['A right angle measures…', '45°|90°|180°|360°', '90°'], ['What is 1000 ÷ 25?', '20|25|40|50', '40'], ['If 5 pens cost 50, one costs…', '5|10|15|20', '10'], ['Area of rectangle 5 by 3 is…', '8|15|16|20', '15'], ['What is 7² − 3²?', '16|40|46|58', '40']],
    'Computer Science': [['What does CPU stand for?', 'Central Processing Unit|Computer Personal Unit|Core Program Utility|Central Print Unit', 'Central Processing Unit'], ['Binary uses which digits?', '1 and 2|0 and 1|2 and 3|A and B', '0 and 1'], ['HTML is used to create…', 'Web pages|Databases|Viruses|Printers', 'Web pages'], ['Which is an operating system?', 'Python|Linux|HTML|HTTP', 'Linux'], ['RAM is…', 'Permanent storage|Volatile memory|A processor|A cable', 'Volatile memory'], ['What does URL stand for?', 'Uniform Resource Locator|User Route Link|Universal Read Line|Unit Record List', 'Uniform Resource Locator'], ['A computer virus is a…', 'Hardware|Malicious program|Monitor|Network cable', 'Malicious program'], ['Which is a programming language?', 'Python|Pixel|Router|Cursor', 'Python'], ['What does WWW stand for?', 'World Wide Web|Wide World Word|Web Wide Window|World Web Wire', 'World Wide Web'], ['A database stores…', 'Organized data|Electricity|Screens|Sound only', 'Organized data'], ['Which device outputs a hard copy?', 'Scanner|Printer|Mouse|Router', 'Printer'], ['The brain of a computer is commonly called…', 'CPU|Keyboard|RAM|Monitor', 'CPU'], ['Phishing attempts to steal…', 'Personal information|Power|Screen size|Files only', 'Personal information'], ['An algorithm is a…', 'Step-by-step procedure|Picture|Device|Password', 'Step-by-step procedure'], ['Cloud computing uses…', 'Remote internet servers|Only paper|A calculator|A keyboard', 'Remote internet servers']],
  };
  final result = <Question>[];
  var n = 1;
  banks.forEach((subject, items) { for (var i = 0; i < items.length; i++) { final x = items[i]; final opts = x[1].split('|'); result.add(Question(id: 'q$n', subject: subject, text: x[0], options: opts, answer: opts.indexOf(x[2]), difficulty: i % 3 == 0 ? 'Easy' : i % 3 == 1 ? 'Medium' : 'Hard', explanation: 'The correct answer is “${x[2]}”. Review this topic and try another question.')); n++; } });
  final seed = List<Question>.from(result);
  var copy = 0;
  while (result.length < 108) {
    final q = seed[copy % seed.length];
    result.add(Question(id: 'q${result.length + 1}', subject: q.subject, text: '${q.text} (Review)', options: q.options, answer: q.answer, difficulty: q.difficulty, explanation: q.explanation));
    copy++;
  }
  return result;
}
