import 'dart:async';
import 'package:flutter/material.dart';
import 'data.dart';
import 'models.dart';
import 'store.dart';

void main() async { WidgetsFlutterBinding.ensureInitialized(); final store = AppStore(); await store.load(buildQuestions()); runApp(ExamPrepApp(store: store)); }

class ExamPrepApp extends StatelessWidget {
  final AppStore store;
  const ExamPrepApp({super.key, required this.store});
  @override Widget build(BuildContext context) => AnimatedBuilder(animation: store, builder: (_, __) => MaterialApp(debugShowCheckedModeBanner: false, title: 'ExamPrep', themeMode: store.darkMode ? ThemeMode.dark : ThemeMode.light, theme: ThemeData(colorSchemeSeed: const Color(0xff315c9b), useMaterial3: true, scaffoldBackgroundColor: const Color(0xfff7f9fc), inputDecorationTheme: const InputDecorationTheme(border: OutlineInputBorder())), darkTheme: ThemeData(colorSchemeSeed: const Color(0xff8eb7ff), brightness: Brightness.dark, useMaterial3: true), home: Shell(store: store)));
}

class Shell extends StatefulWidget { final AppStore store; const Shell({super.key, required this.store}); @override State<Shell> createState() => _ShellState(); }
class _ShellState extends State<Shell> { int tab = 0; @override Widget build(BuildContext context) { final pages = [Dashboard(store: widget.store, onQuiz: () => setState(() => tab = 1)), QuestionBank(store: widget.store), Planner(store: widget.store), ProgressPage(store: widget.store)]; return Scaffold(body: SafeArea(child: pages[tab]), bottomNavigationBar: NavigationBar(selectedIndex: tab, onDestinationSelected: (i) => setState(() => tab = i), destinations: const [NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home), label: 'Home'), NavigationDestination(icon: Icon(Icons.menu_book_outlined), selectedIcon: Icon(Icons.menu_book), label: 'Question Bank'), NavigationDestination(icon: Icon(Icons.event_note_outlined), selectedIcon: Icon(Icons.event_note), label: 'Planner'), NavigationDestination(icon: Icon(Icons.insights_outlined), selectedIcon: Icon(Icons.insights), label: 'Progress')])); } }

class Dashboard extends StatelessWidget { final AppStore store; final VoidCallback onQuiz; const Dashboard({super.key, required this.store, required this.onQuiz}); @override Widget build(BuildContext context) { final cs = Theme.of(context).colorScheme; return CustomScrollView(slivers: [SliverAppBar(title: const Text('ExamPrep', style: TextStyle(fontWeight: FontWeight.bold)), actions: [IconButton(onPressed: store.toggleTheme, icon: Icon(store.darkMode ? Icons.light_mode : Icons.dark_mode))], floating: true), SliverPadding(padding: const EdgeInsets.all(20), sliver: SliverList(delegate: SliverChildListDelegate([Text('Good morning, learner 👋', style: Theme.of(context).textTheme.titleMedium), const SizedBox(height: 5), Text('Build your knowledge, one question at a time.', style: TextStyle(color: cs.onSurfaceVariant)), const SizedBox(height: 22), _progressCard(context), const SizedBox(height: 22), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text('Practice modes', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)), TextButton(onPressed: onQuiz, child: const Text('View all'))]), const SizedBox(height: 8), Row(children: [_mode(context, Icons.bolt, 'Quick Quiz', '10 questions', onQuiz), const SizedBox(width: 12), _mode(context, Icons.timer_outlined, 'Timed Test', '15 minutes', onQuiz)]), const SizedBox(height: 26), Text('Subjects', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 10), Wrap(spacing: 10, runSpacing: 10, children: subjects.take(6).map((s) => ActionChip(avatar: Icon(_subjectIcon(s), size: 18), label: Text(s), onPressed: onQuiz)).toList()), const SizedBox(height: 24), Text('Your study streak', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 10), Card(child: ListTile(leading: const Icon(Icons.local_fire_department, color: Colors.orange, size: 34), title: Text('${store.streak} day streak'), subtitle: const Text('Keep going — consistency beats intensity.'), trailing: Text('${store.solvedToday}/${store.dailyGoal}')))]))]); }
  Widget _progressCard(BuildContext c) { final cs = Theme.of(c).colorScheme; return Card(color: cs.primary, child: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Today's progress", style: TextStyle(color: cs.onPrimary.withOpacity(.8))), const SizedBox(height: 8), Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Text('${store.solvedToday}', style: TextStyle(fontSize: 36, fontWeight: FontWeight.bold, color: cs.onPrimary)), Text(' / ${store.dailyGoal} questions', style: TextStyle(color: cs.onPrimary.withOpacity(.8)))]), const SizedBox(height: 14), ClipRRect(borderRadius: BorderRadius.circular(10), child: LinearProgressIndicator(value: (store.solvedToday / store.dailyGoal).clamp(0, 1), minHeight: 8, backgroundColor: cs.onPrimary.withOpacity(.2), color: cs.onPrimary)), const SizedBox(height: 16), Row(children: [Text('${(store.accuracy * 100).round()}% accuracy', style: TextStyle(color: cs.onPrimary)), const Spacer(), Text('${store.correct} correct  •  ${store.wrong} wrong', style: TextStyle(color: cs.onPrimary.withOpacity(.8)))])]))); }
  Widget _mode(BuildContext c, IconData icon, String title, String sub, VoidCallback tap) => Expanded(child: Card(child: InkWell(onTap: tap, borderRadius: BorderRadius.circular(12), child: Padding(padding: const EdgeInsets.all(15), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Icon(icon, color: Theme.of(c).colorScheme.primary), const SizedBox(height: 12), Text(title, style: const TextStyle(fontWeight: FontWeight.bold)), Text(sub, style: Theme.of(c).textTheme.bodySmall)]))));
  IconData _subjectIcon(String s) => s == 'Mathematics' ? Icons.calculate_outlined : s == 'Computer Science' ? Icons.computer : s == 'English Grammar' ? Icons.translate : Icons.public;
}

class QuestionBank extends StatefulWidget { final AppStore store; const QuestionBank({super.key, required this.store}); @override State<QuestionBank> createState() => _QuestionBankState(); }
class _QuestionBankState extends State<QuestionBank> { String query = '', filter = 'All'; @override Widget build(BuildContext context) { final qs = widget.store.questions.where((q) => (filter == 'All' || q.subject == filter) && q.text.toLowerCase().contains(query.toLowerCase())).toList(); return Column(children: [AppBar(title: const Text('Question Bank'), actions: [IconButton(onPressed: () => _start(qs), icon: const Icon(Icons.play_arrow))]), Padding(padding: const EdgeInsets.fromLTRB(16, 4, 16, 8), child: TextField(decoration: const InputDecoration(prefixIcon: Icon(Icons.search), hintText: 'Search questions'), onChanged: (v) => setState(() => query = v))), SizedBox(height: 45, child: ListView(scrollDirection: Axis.horizontal, padding: const EdgeInsets.symmetric(horizontal: 16), children: ['All', ...subjects].map((s) => Padding(padding: const EdgeInsets.only(right: 8), child: ChoiceChip(label: Text(s), selected: filter == s, onSelected: (_) => setState(() => filter = s))).toList())), Expanded(child: ListView.builder(itemCount: qs.length, itemBuilder: (_, i) { final q = qs[i]; return ListTile(leading: CircleAvatar(child: Text('${i + 1}')), title: Text(q.text, maxLines: 2, overflow: TextOverflow.ellipsis), subtitle: Text('${q.subject}  •  ${q.difficulty}'), trailing: IconButton(icon: Icon(widget.store.bookmarks.contains(q.id) ? Icons.bookmark : Icons.bookmark_border), onPressed: () => widget.store.toggleBookmark(q)); })))]); }
  void _start(List<Question> qs) { if (qs.isNotEmpty) Navigator.push(context, MaterialPageRoute(builder: (_) => QuizPage(store: widget.store, questions: qs.take(10).toList(), title: 'Practice Quiz'))); }
}

class QuizPage extends StatefulWidget { final AppStore store; final List<Question> questions; final String title; const QuizPage({super.key, required this.store, required this.questions, required this.title}); @override State<QuizPage> createState() => _QuizPageState(); }
class _QuizPageState extends State<QuizPage> { int index = 0, selected = -1, correct = 0, seconds = 900; Timer? timer; bool answered = false; @override void initState() { super.initState(); timer = Timer.periodic(const Duration(seconds: 1), (_) { if (seconds > 0) setState(() => seconds--); else _finish(); }); } @override void dispose() { timer?.cancel(); super.dispose(); } @override Widget build(BuildContext context) { final q = widget.questions[index]; return Scaffold(appBar: AppBar(title: Text(widget.title), actions: [Text('${seconds ~/ 60}:${(seconds % 60).toString().padLeft(2, '0')}'), const SizedBox(width: 16)]), body: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [LinearProgressIndicator(value: (index + 1) / widget.questions.length), const SizedBox(height: 24), Text('Question ${index + 1} of ${widget.questions.length}', style: TextStyle(color: Theme.of(context).colorScheme.primary, fontWeight: FontWeight.bold)), const SizedBox(height: 12), Text(q.text, style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 22), ...q.options.asMap().entries.map((e) => _option(q, e.key, e.value)), if (answered) Card(color: selected == q.answer ? Colors.green.withOpacity(.12) : Colors.red.withOpacity(.12), child: Padding(padding: const EdgeInsets.all(14), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Icon(selected == q.answer ? Icons.check_circle : Icons.info, color: selected == q.answer ? Colors.green : Colors.red), const SizedBox(width: 10), Expanded(child: Text(q.explanation))]))), const Spacer(), SizedBox(width: double.infinity, child: FilledButton(onPressed: answered ? _next : null, child: Text(index == widget.questions.length - 1 ? 'Finish quiz' : 'Next question')))])); }
  Widget _option(Question q, int i, String text) { final chosen = selected == i; final right = answered && i == q.answer; return Card(color: right ? Colors.green.withOpacity(.15) : (answered && chosen ? Colors.red.withOpacity(.15) : null), child: RadioListTile<int>(value: i, groupValue: selected, onChanged: answered ? null : (v) => setState(() { selected = v!; answered = true; widget.store.answer(q, v == q.answer); if (v == q.answer) correct++; }), title: Text(text), secondary: answered && right ? const Icon(Icons.check, color: Colors.green) : null)); }
  void _next() { if (index == widget.questions.length - 1) _finish(); else setState(() { index++; selected = -1; answered = false; }); }
  void _finish() { timer?.cancel(); Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => ResultPage(correct: correct, total: widget.questions.length, title: widget.title))); }
}

class ResultPage extends StatelessWidget { final int correct, total; final String title; const ResultPage({super.key, required this.correct, required this.total, required this.title}); @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Quiz complete')), body: Center(child: Padding(padding: const EdgeInsets.all(24), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Icon(correct >= total / 2 ? Icons.emoji_events : Icons.refresh, size: 78, color: Theme.of(context).colorScheme.primary), const SizedBox(height: 20), Text('Great work!', style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 8), Text('$title results'), const SizedBox(height: 28), Text('$correct / $total', style: const TextStyle(fontSize: 48, fontWeight: FontWeight.bold)), Text('${(correct / total * 100).round()}% accuracy'), const SizedBox(height: 28), FilledButton(onPressed: () => Navigator.pop(context), child: const Text('Back to dashboard'))])));
}

class Planner extends StatefulWidget { final AppStore store; const Planner({super.key, required this.store}); @override State<Planner> createState() => _PlannerState(); }
class _PlannerState extends State<Planner> { void add() { final c = TextEditingController(); showDialog(context: context, builder: (_) => AlertDialog(title: const Text('New study task'), content: TextField(controller: c, autofocus: true, decoration: const InputDecoration(hintText: 'e.g. Revise Mathematics')), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () { widget.store.addTask(c.text); Navigator.pop(context); }, child: const Text('Add'))])); } @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Study planner'), actions: [IconButton(onPressed: add, icon: const Icon(Icons.add))]), body: ListView(padding: const EdgeInsets.all(16), children: [Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Daily goal', style: Theme.of(context).textTheme.titleMedium), const SizedBox(height: 8), Text('${widget.store.solvedToday} of ${widget.store.dailyGoal} questions completed'), const SizedBox(height: 10), LinearProgressIndicator(value: (widget.store.solvedToday / widget.store.dailyGoal).clamp(0, 1))])), const SizedBox(height: 18), Text('Today\'s tasks', style: Theme.of(context).textTheme.titleLarge), ...widget.store.tasks.asMap().entries.map((e) => Card(child: CheckboxListTile(value: false, onChanged: (_) => widget.store.removeTask(e.key), title: Text(e.value), subtitle: const Text('Tap to mark complete'))))])); }
}

class ProgressPage extends StatelessWidget { final AppStore store; const ProgressPage({super.key, required this.store}); @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Your progress')), body: ListView(padding: const EdgeInsets.all(16), children: [Card(child: Padding(padding: const EdgeInsets.all(20), child: Column(children: [Text('${(store.accuracy * 100).round()}%', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.bold)), const Text('Overall accuracy'), const SizedBox(height: 18), LinearProgressIndicator(value: store.accuracy)])), const SizedBox(height: 14), Row(children: [_stat(context, 'Solved', '${store.correct + store.wrong}', Icons.task_alt), _stat(context, 'Correct', '${store.correct}', Icons.check_circle), _stat(context, 'Wrong', '${store.wrong}', Icons.cancel)]), const SizedBox(height: 20), Text('Performance overview', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 8), ...subjects.map((s) { final total = store.questions.where((q) => q.subject == s && store.attempted.contains(q.id)).length; return ListTile(title: Text(s), subtitle: Text('$total questions attempted'), trailing: const Icon(Icons.chevron_right))) ])); }
  Widget _stat(BuildContext c, String label, String value, IconData icon) => Expanded(child: Card(child: Padding(padding: const EdgeInsets.symmetric(vertical: 16), child: Column(children: [Icon(icon, color: Theme.of(c).colorScheme.primary), const SizedBox(height: 6), Text(value, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)), Text(label, style: Theme.of(c).textTheme.bodySmall)]))));
}
